# Generated by Django 5.1.3 on 2025-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Others', 'Others')], default='Islam', max_length=15),
        ),
    ]
