# Generated by Django 5.1.3 on 2025-06-27 17:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjSavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('maturity_years', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_deposit_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
