# Generated by Django 5.1.3 on 2025-06-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hajjsavingsaccount',
            name='goal_amount',
        ),
        migrations.RemoveField(
            model_name='hajjsavingsaccount',
            name='maturity_years',
        ),
        migrations.RemoveField(
            model_name='hajjsavingsaccount',
            name='start_date',
        ),
        migrations.AddField(
            model_name='hajjsavingsaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='hajjsavingsaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
